### ISSUE TITLE
adaptor.js 重复执行

### ISSUE THREAD

**Issue by caoyongxi** [wuba/wwto#1]
在转支付宝小程序时，分包加载打开对应的page页面时，adaptor.js重复执行，导致小程序应用下wx对象下的方法被多次重写

建议修复：
路径：src/adaptor/src/alibaba.js 修改如下：

原始代码：
function getInstance() {
  // eslint-disable-next-line no-undef
  const wx = my;
  wx.has_ali_hook_flag = true;

  ........

  return wx;
}

修改后代码：
function getInstance() {
  // eslint-disable-next-line no-undef
  const wx = my;
  // fix 重复执行
  if (wx.has_ali_hook_flag) {
    return wx;
  }
  wx.has_ali_hook_flag = true;
 
  ........

  return wx;
}

**Comment by levin1997** [comment]
感谢建议，请提交PR。
