### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by ws15239494106** [wuba/wwto#2]
`npm i`
`...`
`npm ERR! notarget No matching version found for eslint-plugin-node@^11.0.0`
`...`

建议
pages.json：
"eslint-plugin-node": "^11.0.0" => "eslint-plugin-node": "^10.0.0"

**Comment by levin1997** [comment]
存在v11.0.0版本。https://www.npmjs.com/package/eslint-plugin-node/v/11.0.0

**Comment by levin1997** [comment]
存在v11.0.0版本。https://www.npmjs.com/package/eslint-plugin-node/v/11.0.0
